version: '3.3'

services:
  mage:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: mage:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_ROOT_INITIAL_PASSWORD=a
      - MAGE_CREATE_DEMO_DATA=True
    volumes:
      - sqlitedata:/code/deployment/db:rw

volumes:
  sqlitedata:
